
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
    - "master"
    - /v.*$/

install: ./.travis.install.sh

script:
  - make doc
  - make mypy
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make test; fi'

cache: pip
